### ISSUE TITLE
Can't get historical features as Dataframe

### ISSUE THREAD

**Issue by cpatrickalves** [nossrannug/feast-postgres#17] opened 2022-02-22 19:46 UTC
Hi there, 

I am not sure if I am missing something. 
But I've downgraded my feast version to 0.16.0 and used feast-postgres 0.2.4

When I try to get the historical features I get this:

```
 entity_df = pd.DataFrame.from_dict(
        {
            "Id": [893, 414, 523],
            "event_timestamp": datetime(2022, 2, 10, 15, 28, 28),
        }
    )
    
job = store.get_historical_features(
        entity_df=entity_df,
        features=["houses_features:YrSold", "houses_features:SaleCondition", "houses_features:SalePrice"],
    )
    
training_df = job.to_df()
```

```
Traceback (most recent call last):
  File "examples/houses_read_features.py", line 85, in <module>
    hist_features = get_historical_features(store, entity_df)
  File "examples/houses_read_features.py", line 30, in get_historical_features
    training_df = job.to_df()
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/site-packages/feast/infra/offline_stores/offline_store.py", line 43, in to_df
    features_df = self._to_df_internal()
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/site-packages/feast_postgres/offline_stores/postgres.py", line 204, in _to_df_internal
    return self._to_arrow_internal().to_pandas()
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/site-packages/feast_postgres/offline_stores/postgres.py", line 211, in _to_arrow_internal
    with self._query_generator() as query:
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/site-packages/feast_postgres/offline_stores/postgres.py", line 131, in query_generator
    query_context = offline_utils.get_feature_view_query_context(
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/site-packages/feast/infra/offline_stores/offline_utils.py", line 145, in get_feature_view_query_context
    table_subquery=feature_view.input.get_table_query_string(),
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/site-packages/feast/data_source.py", line 419, in get_table_query_string
    raise NotImplementedError
NotImplementedError
```

Seems the method `to.df()` was not implemented in that version. Is that right?
How could be the right way to get my data as a DF?

**Comment by cpatrickalves** [comment] 2022-02-22 20:54
I've also tried with feast 0.15.0
Got the same error.

**Comment by nossrannug** [comment] 2022-02-23 11:13
Can you try reinstalling feast-postgres? The method is implemented https://github.com/nossrannug/feast-postgres/blob/main/feast_postgres/offline_stores/postgres_source.py#L87-L88

**Comment by cpatrickalves** [comment] 2022-02-24 00:38
Thanks for the answer @nossrannug 
I've tried, but get the same result. 

Here are the steps I've made:

1. Create feature store with Postgres as registry and offline Store and Redis as Online store

```
project: xxxxx_repo
provider: local                    

registry:
    registry_store_type: feast_postgres.PostgreSQLRegistryStore
    path: feast_registry            
    host: localhost
    port: 5432                      
    database: postgres
    db_schema: my_schema
    user: admin
    password: admin

offline_store:
    type: feast_postgres.PostgreSQLOfflineStore
    host: localhost
    port: 5432
    database: postgres
    db_schema: my_schema
    user: admin
    password: admin

online_store:
  type: redis
  connection_string: "localhost:6379,password=redis"
```

2. Setup a Docker compose with Redis and PostgreSQL with port and volumes mapped.
3. Create a NEW `conda` env with python 3.8

```
conda create -n featurestore python=3.8
conda activate featurestore
```

4. Install requirements.txt: 
```
feast[redis]==0.16.0
feast-postgres==0.2.4
```

5. Ran `feast apply`

```
Registered entity Id
Registered feature view houses_features
Deploying infrastructure for houses_features
```

6. Try to get historical features using the code above:

```
#from feast.infra.offline_stores.file import SavedDatasetFileStorage
from feast import FeatureStore
import pandas as pd
from datetime import datetime


# repo_path points to the directory where the feature_store.yaml is stored
store = FeatureStore(repo_path=".")

entity_df = pd.DataFrame.from_dict(
    {
        "Id": [893, 414, 523],
        "event_timestamp": datetime(2022, 2, 10, 15, 28, 28),
    })

job = store.get_historical_features(
    entity_df=entity_df,
    features=["houses_features:YrSold", "houses_features:SaleCondition", "houses_features:SalePrice"],
)

job.to_df()
```

7. Got the error:

```
Traceback (most recent call last):
  File "house_test.py", line 21, in <module>
    job.to_df()
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/site-packages/feast/infra/offline_stores/offline_store.py", line 43, in to_df
    features_df = self._to_df_internal()
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/site-packages/feast_postgres/offline_stores/postgres.py", line 204, in _to_df_internal
    return self._to_arrow_internal().to_pandas()
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/site-packages/feast_postgres/offline_stores/postgres.py", line 211, in _to_arrow_internal
    with self._query_generator() as query:
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/site-packages/feast_postgres/offline_stores/postgres.py", line 131, in query_generator
    query_context = offline_utils.get_feature_view_query_context(
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/site-packages/feast/infra/offline_stores/offline_utils.py", line 145, in get_feature_view_query_context
    table_subquery=feature_view.input.get_table_query_string(),
  File "/home/ubuntu/miniconda/envs/featurestore/lib/python3.8/site-packages/feast/data_source.py", line 419, in get_table_query_string
    raise NotImplementedError
NotImplementedError
```

Am I missing something?

Any ideas?

**Comment by nossrannug** [comment] 2022-02-27 10:45
It seems to be an issue with your setup. The last file mentioned in the stack trace shouldn't be called. It should be calling this method: https://github.com/nossrannug/feast-postgres/blob/main/feast_postgres/offline_stores/postgres_source.py#L87 in this postgres_source file.

Can you create a small repo with code and steps to reproduce the issue?

**Comment by cpatrickalves** [comment] 2022-02-28 11:49
Thanks again @nossrannug 

Here is the repo: https://github.com/cpatrickalves/fsissue

**Comment by nossrannug** [comment] 2022-02-28 13:47
The data source needs to match the offline store.

You need to change your offline_store in the yaml to `file` to use the FileSource. Or change the file source to be a `PostgreSQLSource`

```python
# defines the feature source location
house_data_batch = FileSource(
    path="data/raw/houses.parquet",
    event_timestamp_column="created",
)
```

**Comment by cpatrickalves** [comment] 2022-02-28 14:09
>> The data source needs to match the offline store.
I did not know that. 
I thought It will load the parquet file in the SQL DB (offline store).

>> change the file source to be a PostgreSQLSource
In this case, do I need to load all data in some SQL database?  I have parquet files with + 10GB of data =(

**Comment by nossrannug** [comment] 2022-02-28 14:39
Feast connects to an existing data source and treats that as the offline store. So you could have the parquet be the offline store. To use postgres offline store you'll need to get all the data into postgres first.
But you could have the parquet as the offline store and redis as online store and call `feast materialize` to populate redis with data from the file.

**Comment by cpatrickalves** [comment] 2022-02-28 14:51
I got now. 
I've miss understood offline stores.

My point to using PostgreSQL is that I have a multiuser environment, so sharing parquet files would be difficult. 
Having all the data in an online DB would be better. 

I've checked the script you have to load parquet files in DB (`copy_parquet_to_postgres.py`).

You have a `con.execute("DROP TABLE IF EXISTS " + table)` on it. 
Wouldn't this be a bad practice as you will lose all historical data? 


Thanks @nossrannug 

I really appreciate your help.

**Comment by nossrannug** [comment] 2022-02-28 17:33
Yes. This script is not meant for production. This is simply to copy the parquet that comes with the feast example to postgres so that feast-postgres can be tested. but you might be able to use it, with some modifications, to move your parquet to postgres as a one time thing.

**Comment by nossrannug** [comment] 2022-03-01 10:53
I'll go ahead and close this issue. If there is anything else you can open a new issue or ping me on the Feast slack.

**Closed by nossrannug** 2022-03-01 10:53 UTC

**Comment by cpatrickalves** [comment] 2022-03-01 11:25
Everything work as expected now.
Thanks!
